CREATE OR REPLACE PROCEDURE DDPROJ_SP (
    Pro_ID IN DD_PROJECT.IDPROJ%type,
    d_project OUT DD_PROJECT%ROWTYPE
) IS
    TYPE PRO IS RECORD(
        IDPROJ DD_PROJECT.IDPROJ%TYPE,
        PROJNAME DD_PROJECT.PROJNAME%TYPE,
        PROJSTARTDATE DD_PROJECT.PROJSTARTDATE%TYPE,
        PROJENDDATE DD_PROJECT.PROJENDDATE%TYPE,
        PROJFUNDGOAL DD_PROJECT.PROJFUNDGOAL%TYPE,
        PROJCOORD DD_PROJECT.PROJCOORD%TYPE
    );
    D_PRO PRO;
BEGIN
    SELECT
        * INTO d_project
    FROM
        DD_PROJECT
    WHERE
        IDPROJ = Pro_ID;
END DDPROJ_SP;
