CREATE OR REPLACE PROCEDURE DDCKPAY_SP (
    P_ID IN NUMBER,
    P_AMT IN NUMBER,
    RESPONCE OUT VARCHAR2
) IS
    M_MONTH   DD_PLEDGE.PAYMONTHS%TYPE;
    M_ID      DD_PLEDGE.IDPLEDGE%TYPE;
    M_AMT     DD_PLEDGE.PLEDGEAMT%TYPE;
    FINAL_AMT DD_PLEDGE.PLEDGEAMT%TYPE;
    NO_MONTH EXCEPTION;
BEGIN
    SELECT
        IDPLEDGE,
        PLEDGEAMT,
        PAYMONTHS INTO M_ID,
        M_AMT,
        M_MONTH
    FROM
        DD_PLEDGE
    WHERE
        IDPLEDGE = P_ID;
    IF M_MONTH = 0 THEN
        RAISE NO_MONTH;
    END IF;

    FINAL_AMT := M_AMT /M_MONTH;
    IF P_AMT = FINAL_AMT THEN
        RESPONCE := 'CORRECT PAYMENT';
    ELSIF P_AMT != FINAL_AMT THEN
        RAISE_APPLICATION_ERROR(-20050, 'Incorrect payment amount - planned payment = '
                                        || FINAL_AMT);
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No payment information');
    WHEN NO_MONTH THEN
        DBMS_OUTPUT.PUT_LINE('No payment information');
END DDCKPAY_SP;
